services:
  app:
    image: maven:3.8.4-openjdk-17
    container_name: service-auth
    volumes:
      - ./:/src
      - ~/.m2:/root/.m2
    working_dir: /src
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/authdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db

  pgadmin:
    image: elestio/pgadmin
    container_name: service-auth_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=darcanf.94@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=darcan94
    volumes:
      - pgadmin51:/var/lib/pgadmin
    ports:
      - 5058:80
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres
    container_name: service-auth_db
    environment:
      - POSTGRES_DB=authdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    shm_size: 128mb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
  pgadmin51:
